### ISSUE TITLE
你好，作者，有几个问题请教一下

### ISSUE THREAD

**Issue by XPoet** [PasteUs/HelloCI#27]
1、git commit 时，该怎么填写描述，才能匹配上 label ? 可否给个示例
2、我这边 action 生成的 Draft，最终还要自己手动 release ？我看你的发布也自动的，这一步，怎么弄呢？

**Comment by FalconWu2017** [comment]
你确定作者懂中文？

**Comment by lihuacai168** [comment]
> 你确定作者懂中文？

我从作者的CSDN博客过来~肯定懂中文啦

**Comment by lihuacai168** [comment]
我Fork之后，提交了几个之后，触发了release draft，但是发布的内容是空的。不知道什么原因。
![image](https://user-images.githubusercontent.com/11568297/111033220-0d91ba80-844b-11eb-9104-02618beb0be7.png)

![image](https://user-images.githubusercontent.com/11568297/111033166-d9b69500-844a-11eb-9482-fa83fa9154b6.png)

**Comment by lihuacai168** [comment]
> 1、git commit 时，该怎么填写描述，才能匹配上 label ? 可否给个示例
> 2、我这边 action 生成的 Draft，最终还要自己手动 release ？我看你的发布也自动的，这一步，怎么弄呢？

匹配lable不是根据git commit实现的，而是要创建pull request，然后在merge pull request的时候指定labels。

**Comment by LucienShui** [comment]
啊，今天才看到这个 Project 下还有 issue，感谢各位小伙伴的认可。Orz

首先我是国人，只是在 GitHub 上有时候用英文，我的 GitHub 主页也有注明我来自杭州。

关于楼主的问题，楼上已经回答得比较全面的，我再略作补充：

> 1、git commit 时，该怎么填写描述，才能匹配上 label ? 可否给个示例
> 2、我这边 action 生成的 Draft，最终还要自己手动 release ？我看你的发布也自动的，这一步，怎么弄呢？

1. release draft 在每次 commit 时会生成
2. 只有 pull request 会对 release draft 的内容产生影响，pull request 的标题对应 release 中的条目，pull request 的 label 对应 release 中的分类
3. release-drafter 只负责生成 draft 的内容，将 draft 变成 release 这一步还是人为操作的哈

如果还有什么问题的话，欢迎继续盖楼～
